//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evento.EventoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EventoService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEventsForUser", ReplyAction="*")]
        Evento.EventoService.GetEventsForUserResponse GetEventsForUser(Evento.EventoService.GetEventsForUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsForUser", Namespace="http://tempuri.org/", Order=0)]
        public Evento.EventoService.GetEventsForUserRequestBody Body;
        
        public GetEventsForUserRequest() {
        }
        
        public GetEventsForUserRequest(Evento.EventoService.GetEventsForUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventsForUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetEventsForUserRequestBody() {
        }
        
        public GetEventsForUserRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsForUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Evento.EventoService.GetEventsForUserResponseBody Body;
        
        public GetEventsForUserResponse() {
        }
        
        public GetEventsForUserResponse(Evento.EventoService.GetEventsForUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventsForUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEventsForUserResult;
        
        public GetEventsForUserResponseBody() {
        }
        
        public GetEventsForUserResponseBody(string GetEventsForUserResult) {
            this.GetEventsForUserResult = GetEventsForUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Evento.EventoService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Evento.EventoService.Service1Soap>, Evento.EventoService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Evento.EventoService.GetEventsForUserResponse Evento.EventoService.Service1Soap.GetEventsForUser(Evento.EventoService.GetEventsForUserRequest request) {
            return base.Channel.GetEventsForUser(request);
        }
        
        public string GetEventsForUser(string userName) {
            Evento.EventoService.GetEventsForUserRequest inValue = new Evento.EventoService.GetEventsForUserRequest();
            inValue.Body = new Evento.EventoService.GetEventsForUserRequestBody();
            inValue.Body.userName = userName;
            Evento.EventoService.GetEventsForUserResponse retVal = ((Evento.EventoService.Service1Soap)(this)).GetEventsForUser(inValue);
            return retVal.Body.GetEventsForUserResult;
        }
    }
}
